apiVersion: v1
kind: Service
metadata:
  name: my-service-eval
    #labels:
    #app: my-api
spec:
  type: ClusterIP
  selector:
    app: my-api
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000