apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-ingress-eval
spec:
  ingressClassName: traefik
  rules:
  - http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: my-service-fastapi
              port: 
                number: 8000